import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import os
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

# --- CONFIGURATION ---
MANIFEST_PATH = "cnn_training_manifest.csv"
BATCH_SIZE = 32
EPOCHS = 20
IMG_SIZE = (224, 224) # MobileNetV2 standard input shape
# ---------------------

print("--- INITIALIZING MULTI-COHORT CNN TRAINING ---")

# 1. Load the flat manifest generated by your processor script
# --- STEP 1: LOAD AND SANITIZE MANIFEST ---
if not os.path.exists(MANIFEST_PATH):
    raise FileNotFoundError(f"Could not find manifest at {MANIFEST_PATH}.")

df_manifest = pd.read_csv(MANIFEST_PATH)
print(f"Loaded manifest with {len(df_manifest)} total conjunctiva image entries.")

# --- NEW SANITIZATION LOOP ---
print("Validating image file integrity before training...")
from PIL import Image

corrupt_indices = []

for idx, row in df_manifest.iterrows():
    img_path = row["absolute_image_path"]
    try:
        # Try opening and verifying the image structure
        with Image.open(img_path) as img:
            img.verify() 
    except Exception as e:
        print(f"[CORRUPT FILE FOUND] Skipping: {img_path} | Error: {e}")
        corrupt_indices.append(idx)

if corrupt_indices:
    print(f"\n[WARNING] Found {len(corrupt_indices)} corrupted image(s). Cleaning them from the matrix...")
    df_manifest.drop(index=corrupt_indices, inplace=True)
    df_manifest.reset_index(drop=True, inplace=True)
    print(f"Sanitized manifest size: {len(df_manifest)} images remaining.")
else:
    print("All image files verified successfully!")
# ------------------------------

# 2. Data Augmentation (Keeps the model from over-memorizing studio lightning differences)
datagen = ImageDataGenerator(
    rescale=1.0/255.0,
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    fill_mode='nearest',
    validation_split=0.2 # Automatically reserve 20% of images to evaluate accuracy
)

# Training Stream
train_generator = datagen.flow_from_dataframe(
    dataframe=df_manifest,
    directory=None, # Crucial: None tells Keras to read absolute paths straight from the column
    x_col="absolute_image_path",
    y_col="hb_target",
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='raw', # Tells the network to predict a continuous numerical value
    subset='training',
    shuffle=True,
    seed=42
)

# Validation Stream
val_generator = datagen.flow_from_dataframe(
    dataframe=df_manifest,
    directory=None,
    x_col="absolute_image_path",
    y_col="hb_target",
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='raw',
    subset='validation',
    shuffle=False
)

# 3. Import MobileNetV2 with Pre-trained ImageNet weights
print("\nLoading MobileNetV2 Feature Extractor...")
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False # Freeze the base layers so we protect original edge-detection weights

# 4. Append Custom Eyelid-Pallor Regression Architecture
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.4)(x) # Prevents overfitting to specific country skin textures
x = Dense(64, activation='relu')(x)
predictions = Dense(1, activation='linear')(x) # Single output node for continuous g/dL estimation

model = Model(inputs=base_model.input, outputs=predictions)

# 5. Compile and Run Training
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='mean_absolute_error', # MAE mirrors exactly how many g/dL the AI is off by
    metrics=['mae', 'mse']
)

print("\nTraining the Custom Regression Head...")
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=EPOCHS,
    verbose=1
)

# 6. Fine-Tuning Phase (Unfreeze top layers for deep domain adaptation)
print("\nUnfreezing deep layers for fine-tuning...")
base_model.trainable = True
for layer in base_model.layers[:100]: # Leave the lower 100 structural layers frozen
    layer.trainable = False

model.compile(
    optimizer=Adam(learning_rate=0.0001), # Low learning rate to avoid destroying weights
    loss='mean_absolute_error',
    metrics=['mae']
)

print("Running Fine-Tuning Optimization...")
model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10,
    verbose=1
)

# 7. Compress Architecture to TensorFlow Lite for the Raspberry Pi
print("\nTraining Complete! Exporting to TFLite...")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT] # Optimized for hardware execution speeds
tflite_model = converter.convert()

OUTPUT_TFLITE = "eyelid_anemia_model.tflite"
with open(OUTPUT_TFLITE, 'wb') as f:
    f.write(tflite_model)

print(f"\nSUCCESS! Micro-model binary compiled as: {OUTPUT_TFLITE}")
print("Download this file and copy it into your main Raspberry Pi repository directory.")